spring:
  cloud:
    gateway:
        routes:
          - id : r1
            uri : http://localhost:9090/
            predicates :
              - Path=/customers/**
          - id: r2
            uri: http://localhost:9091/
            predicates:
              - Path=/accounts/**
  application:
    name: gateway-service
server:
  port: 8888